* Enno Basteln

** Installation

https://docs.micropython.org/en/latest/esp32/tutorial/intro.html


#+begin_src
 pip install esptool adafruit-ampy
 pipenv run esptool.py --chip esp32 --port /dev/tty.usbserial-0001 erase_flash
#+end_src

Download https://micropython.org/resources/firmware/esp32-20230426-v1.20.0.bin

#+begin_src
esptool.py --chip esp32 --port /dev/tty.usbserial-0001 --baud 460800 write_flash -z 0x1000 ~/Downloads/esp32-20230426-v1.20.0.bin
#+end_src


** Connecting to uPy REPL

#+begin_src
screen /dev/tty.usbserial-0001 115200
#+end_src

*** Using Copy & Paste Mode

https://docs.micropython.org/en/latest/reference/repl.html#paste-mode

** Deploying Code

=adafruit-ampy= contains the =ampy= command that allows to publish code to the uPy device. Create a main with the following contents:

#+begin_src  python
import time

while True:
  time.sleep_ms(100)
  print("hallo welt")
#+end_src

Then use

#+begin_src bash
ampy --port /dev/tty.usbserial-0001 put main.py
#+end_src

*ATTENTION*: if you can't connect, it might be necessary to go to the
REPL (via screen for example) and C-c the program running. Then =ampy=
might work. If not, additionally remove the =main.py= and possibly =boot.py= via

#+begin_src python
import os;  os.remove("main.py");  os.remove("boot.py")
#+end_src



** ST7735

AZ Delivery: https://www.az-delivery.de/en/products/1-77-zoll-spi-tft-display

https://cdn.shopify.com/s/files/1/1509/1638/files/1.77_inch_TFT_Display_-_pinout.jpg?v=1593150369

Pinout left to right, as seen from top, with the pins pointing away,
and the silkscreen text '1.77" 160(RGB)x128' at the bottom.


|-----+------------+-----------+-------|
| Pin | Silkscreen | Function  | ESP32 |
|-----+------------+-----------+-------|
|   1 | GND        | GND       | GND   |
|   2 | VCC        | VCC       | 3V3   |
|   3 | SCK        | SPI CLK   | G14   |
|   4 | SDA        | SPI MOSI  | G13   |
|   5 | RES        | Reset     | G17   |
|   6 | RS         | DC        | G16   |
|   7 | CS         | CS        | G18   |
|   8 | LEDA       | Backlight | 3V3   |
|-----+------------+-----------+-------|


uPy driver from https://github.com/boochow/MicroPython-ST7735


** Mosquitto

*** Mac

Installed and run via =homebrew=

#+begin_src bash
brew install mosquitto
brew services start mosquitto
#+end_src

Configuration file:

#+begin_src bash
  /opt/homebrew/etc/mosquitto/mosquitto.conf
#+end_src
